=== erczo/dendro-nosql-json/schemas/datastream.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id": {"$ref": "#/definitions/objectId"},
    "attributes": {"type": "object"},
    "created_at": {"$ref": "#/definitions/isoDate"},
    "datapoints_config": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "begins_at": {"$ref": "#/definitions/isoDate"},
          "ends_before": {"$ref": "#/definitions/isoDate"},
          "params": {"type": "object"},
          "path": {"type": "string"}
        },
        "required": ["params", "path"],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "derivation_description": {"type": "string"},
    "derived": {"type": "boolean"},
    "description": {"type": "string"},
    "enabled": {"type": "boolean"},
    "geo": {
      "type": "object",
      "properties": {
        "coordinates": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 2,
          "maxItems": 2
        },
        "type": {
          "type": "string",
          "enum": ["Point"]
        }
      },
      "required": ["coordinates", "type"]
    },
    "members": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "organization_id": {"$ref": "#/definitions/objectId"},
          "person_id": {"$ref": "#/definitions/objectId"},
          "roles": {
            "type": "array",
            "items": {"type": "string"},
            "minItems": 1
          }
        },
        "required": ["roles"]
      }
    },
    "name": {"type": "string"},
    "source_type": {
      "type": "string",
      "enum": ["sensor"]
    },
    "state": {
      "type": "string",
      "enum": ["ready"]
    },
    "station_id": {"$ref": "#/definitions/objectId"},
    "tags": {
      "type": "array",
      "items": {"type": "string"},
      "minItems": 1
    },
    "thing_id": {"$ref": "#/definitions/objectId"},
    "urls": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {"type": "string"},
          "url": {
            "type": "string",
            "format": "uri"
          }
        }
      }
    }
  },
  "definitions": {
    "objectId": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{24}$",
      "maxLength": 24
    },
    "isoDate": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}[T][0-9]{2}:[0-9]{2}:[0-9]{2}|.|[0-9]{0,3}Z$"
    }
  },
  "required": ["derived", "enabled", "name"],
  "additionalProperties": false
}

=== erczo/dendro-nosql-json/examples/datastreams/Legacy_Datastream_3075.json
{
  "datapoints_config": [
    {
      "params": {
        "query": {
          "compact": true,
          "datastream_id": 3075,
          "time_adjust": -28800
        }
      },
      "path": "/legacy/datavalues-ucnrs"
    }
  ],
  "derived": false,
  "enabled": true,
  "name": "Blue Oak Ranch Air Temperature degC Maximum",
  "source_type": "sensor",
  "state": "ready",
  "station_id": "5861989eb6e0c00001edb2b2",
  "tags": [
    "ds:Aggregation:Maximum",
    "ds:Medium:Air",
    "ds:Variable:Temperature",
    "dt:Unit:DegreeCelsius"
  ]
}

=== erczo/dendro-nosql-json/examples/datastreams/Legacy_Datastream_3076.json
{
  "datapoints_config": [
    {
      "params": {
        "query": {
          "compact": true,
          "datastream_id": 3076,
          "time_adjust": -28800
        }
      },
      "path": "/legacy/datavalues-ucnrs"
    }
  ],
  "derived": false,
  "enabled": true,
  "name": "Blue Oak Ranch Air Temperature degC Minimum",
  "source_type": "sensor",
  "state": "ready",
  "station_id": "5861989eb6e0c00001edb2b2",
  "tags": [
    "ds:Aggregation:Minimum",
    "ds:Medium:Air",
    "ds:Variable:Temperature",
    "dt:Unit:DegreeCelsius"
  ]
}

=== erczo/dendro-nosql-json/examples/datastreams/Legacy_Datastream_3097.json
{
  "attributes": {
    "depth": 4,
    "unit": "Inch"
  },
  "datapoints_config": [
    {
      "params": {
        "query": {
          "compact": true,
          "datastream_id": 3097,
          "time_adjust": -28800
        }
      },
      "path": "/legacy/datavalues-ucnrs"
    }
  ],
  "derived": false,
  "enabled": true,
  "name": "Soil Temp Deg C 4 in Blue Oak Max",
  "source_type": "sensor",
  "state": "ready",
  "station_id": "5861989eb6e0c00001edb2b2",
  "tags": [
    "ds_Aggregation_Maximum",
    "ds_Medium_Soil",
    "ds_Variable_Temperature",
    "dt_Unit_DegreeCelsius"
  ]
}
