=== erczo/dendro-nosql-json/schemas/place.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string"
    },
    "abbreviation": {
      "type": "string"
    },
    "attributes": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string"
        },
        "postal_code": {
          "type": "string"
        },
        "primary_phone": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "street_address": {
          "type": "string"
        }
      },
      "required": []
    },
    "country_code": {
      "type": "string"
    },
    "created_at": {
      "$ref": "#/definitions/isoDate"
    },
    "updated_at": {
      "$ref": "#/definitions/isoDate"
    },
    "external_refs": {
      "type": "array",
      "items": {
        "type": "object",
        "minItems": 1,
        "properties": {
          "ref_id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["ref_id"]
      }
    },
    "full_name": {
      "type": "string"
    },
    "geo": {
      "type": "object",
      "properties": {
        "coordinates": {
          "type": "array",
          "minItems": 2,
          "maxItems": 3,
          "items": {
            "type": "number"
          }
        },
        "type": {
          "type": "string",
          "enum": ["Point"]
        }
      },
      "required": ["coordinates", "type"]
    },
    "name": {
      "type": "string"
    },
    "place_type": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "format": "uri"
    }
  },
  "definitions": {
    "objectId": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{24}$",
      "maxLength": 24
    },
    "isoDate": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}[T][0-9]{2}:[0-9]{2}:[0-9]{2}|.|[0-9]{0,3}Z$"
    }
  },
  "required": ["geo", "name"],
  "additionalProperties": false
}

=== erczo/dendro-nosql-json/examples/places/Generic_Place.json
{
  "_id": "ChIJPV4oX_65j4ARVW8IJ6IJUYs",
  "abbreviation": "CA",
  "attributes": {
    "city": "",
    "postal_code": "",
    "primary_phone": "",
    "state": "",
    "street_address": ""
  },
  "country_code": "US",
  "created_at": "2016-11-15T16:30:00Z",
  "external_refs": [
    {
      "ref_id": "",
      "type": "google_place_id",
      "url": ""
    }
  ],
  "full_name": "",
  "geo": {
    "coordinates": [
      -122.431297,
      37.773972
    ],
    "type": "Point"
  },
  "name": "California",
  "place_type": "state",
  "url": "http://..."
}
