=== erczo/dendro-nosql-json/schemas/vocabulary.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id": {"type": "string"},
    "created_at": {"$ref": "#/definitions/isoDate"},
    "description": {"type": "string"},
    "label": {"type": "string"},
    "scheme_id": {
      "type": "string",
      "enum": ["ds", "dq", "di", "dt"]
    },
    "terms": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "abbreviation": {"type": "string"},
          "definition": {"type": "string"},
          "label": {"type": "string"},
          "name": {"type": "string"}
        },
        "required": ["label"]
      }
    }
  },
  "definitions": {
    "objectId": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{24}$",
      "maxLength": 24
    },
    "isoDate": {
      "type": "string", 
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}[T][0-9]{2}:[0-9]{2}:[0-9]{2}|.|[0-9]{0,3}Z$"
    }
  },
  "required": ["label", "scheme_id"],
  "additionalProperties": false
}

=== erczo/dendro-nosql-json/examples/vocabularies/ds-time-aggregate.json
{
  "_id": "ds-time-aggregate",
  "created_at": "2017-01-31T09:30:00Z",
  "description": "TBD",
  "label": "Time Aggregate",
  "scheme_id": "ds",
  "terms": [
    {
      "definition": "TBD",
      "label": "WaterYear"
    },
    {
      "definition": "TBD",
      "label": "Year"
    },
    {
      "definition": "TBD",
      "label": "Month"
    },
    {
      "definition": "TBD",
      "label": "Week"
    },
    {
      "definition": "TBD",
      "label": "Day"
    },
    {
      "definition": "TBD",
      "label": "Hour"
    },
        {
      "definition": "TBD",
      "label": "30 Minutes"
    },
    {
      "definition": "TBD",
      "label": "15 Minutes"
    },
    {
      "definition": "TBD",
      "label": "10 Minutes"
    },
    {
      "definition": "TBD",
      "label": "5 Minutes"
    }
  ]
}

=== erczo/dendro-nosql-json/examples/vocabularies/ds-variable.json
{
  "_id": "ds-variable",
  "description": "TBD",
  "label": "Variable",
  "scheme_id": "ds",
  "terms": [
    {
      "definition": "TBD",
      "label": "BarometricPressure",
      "name": "Barometric Pressure"
    },
    {
      "definition": "TBD",
      "label": "Count"
    },
    {
      "definition": "TBD",
      "label": "Depth"
    },
    {
      "definition": "TBD",
      "label": "Description"
    },
    {
      "definition": "TBD",
      "label": "DielectricStrength",
      "name": "Dielectric Strength"
    },
    {
      "definition": "TBD",
      "label": "Direction"
    },
    {
      "definition": "TBD",
      "label": "Discharge"
    },
    {
      "definition": "TBD",
      "label": "Duration"
    },
    {
      "definition": "TBD",
      "label": "Evapotranspiration"
    },
    {
      "definition": "TBD",
      "label": "Flux"
    },
    {
      "definition": "TBD",
      "label": "Height"
    },
    {
      "definition": "TBD",
      "label": "Moisture"
    },
    {
      "definition": "TBD",
      "label": "PhotosyntheticallyActiveRadiation",
      "name": "Photosynthetically Active Radiation"
    },
    {
      "definition": "TBD",
      "label": "Precipitation"
    },
    {
      "definition": "TBD",
      "label": "RelativeHumidity",
      "name": "Relative Humidity"
    },
    {
      "definition": "TBD",
      "label": "SolarRadiation",
      "name": "Solar Radiation"
    },
    {
      "definition": "TBD",
      "label": "Speed"
    },
    {
      "definition": "TBD",
      "label": "Temperature"
    },
    {
      "definition": "TBD",
      "label": "Transpiration"
    },
    {
      "definition": "TBD",
      "label": "Turbidity"
    },
    {
      "definition": "TBD",
      "label": "VaporPressure"
    },
    {
      "definition": "TBD",
      "label": "VaporPressureDeficit",
      "name": "Vapor Pressure Deficit"
    },
    {
      "definition": "TBD",
      "label": "Velocity"
    },
    {
      "definition": "TBD",
      "label": "Visibility"
    },
    {
      "definition": "TBD",
      "label": "Volume"
    },
    {
      "definition": "TBD",
      "label": "VolumetricWaterContent",
      "name": "Volumetric Water Content"
    }
  ]
}

=== erczo/dendro-nosql-json/examples/vocabularies/ds-aggregate.json
{
  "_id": "ds-aggregate",
  "created_at": "2016-11-15T16:30:00Z",
  "description": "TBD",
  "label": "Aggregate",
  "scheme_id": "ds",
  "terms": [
    {
      "definition": "TBD",
      "label": "Average"
    },
    {
      "definition": "TBD",
      "label": "Maximum"
    },
    {
      "definition": "TBD",
      "label": "Median"
    },
    {
      "definition": "TBD",
      "label": "Minimum"
    },
    {
      "definition": "TBD",
      "label": "StandardDeviation"
    },
    {
      "definition": "TBD",
      "label": "Sum"
    }
  ]
}
